[[plugins]]
repo      = 'Shougo/dein.vim'

[[plugins]]
repo      = 'Shougo/vimproc.vim'
build     = 'make'

[[plugins]]
repo      = 'Shougo/neocomplcache.vim'
build     = 'make'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-neocomplcache.vim'

[[plugins]]
repo      = 'Shougo/neosnippet.vim'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-neosnippet.vim'

[[plugins]]
repo      = 'Shougo/neosnippet-snippets'

[[plugins]]
repo      = 'machakann/vim-sandwich'

[[plugins]]
repo      = 'easymotion/vim-easymotion'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-easymotion.vim'

[[plugins]]
repo      = 'scrooloose/nerdtree'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-nerdtree.vim'

[[plugins]]
repo      = 'Xuyuanp/nerdtree-git-plugin'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-nerdtree-git-plugin.vim'

[[plugins]]
repo      = 'airblade/vim-gitgutter'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-vim-gitgutter.vim'

[[plugins]]
repo      = 'tpope/vim-fugitive'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-vim-fugitive.vim'

[[plugins]]
repo      = 'tpope/vim-git'

[[plugins]]
repo      = 'ryanoasis/vim-devicons'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-vim-devicons.vim'

[[plugins]]
repo      = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo      = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo      = 'kien/rainbow_parentheses.vim'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-rainbow_parentheses.vim'

[[plugins]]
repo      = 'nathanaelkane/vim-indent-guides'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-vim-indent-guides.vim'

[[plugins]]
repo      = 'junegunn/vim-easy-align'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-vim-easy-align.vim'

[[plugins]]
repo      = 'valloric/MatchTagAlways'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-matchtagalways.vim'

[[plugins]]
repo      = 'myusuf3/numbers.vim'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-numbers.vim'

[[plugins]]
repo      = 'osyo-manga/vim-precious'
depends   = ['context_filetype.vim']

[[plugins]]
repo      = 'Shougo/context_filetype.vim'

[[plugins]]
repo      = 'tpope/vim-speeddating'

[[plugins]]
repo      = 'itchyny/calendar.vim'

[[plugins]]
repo      = 'deponian/vim-lightline-whitespace'

[[plugins]]
repo      = 'itchyny/lightline.vim'
hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-lightline.vim'

[[plugins]]
repo      = 'yuttie/comfortable-motion.vim'

[[plugins]]
repo      = 'rbtnn/vim-game_engine'

[[plugins]]
repo      = 'rbtnn/puyo.vim'

[[plugins]]
repo      = 'johngrib/vim-game-code-break'

[[plugins]]
repo      = 'sheerun/vim-polyglot'
