[[plugins]]
repo      = 'cespare/vim-toml'
on_ft     = 'toml'

#[[plugins]]
#repo      = 'stanangeloff/php.vim'
#on_ft     = 'php'

#[[plugins]]
#repo      = 'rayburgemeestre/phpfolding.vim'
#on_ft     = 'php'
#hook_add  = 'source ~/.config/nvim/rc/plugins/plugins-phpfolding.vim'

[[plugins]]
repo      = 'pangloss/vim-javascript'
on_ft     = 'js'

[[plugins]]
repo      = 'hail2u/vim-css3-syntax'
on_ft     = ['css', 'scss']
